branch-defaults:
  default:
    environment: Itsag1t42022backend-env
environment-defaults:
  Itsag1t42022backend-env:
    branch: null
    repository: null
global:
  application_name: ITSA-G1T4-2022-Backend
  default_ec2_keyname: null
  default_platform: Python 3.8 running on 64bit Amazon Linux 2
  default_region: ap-southeast-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  sc: null
  workspace_type: Application
